version: '3.9'

services:
  nestjs-backend:
    image: yc4852/nestjs-backend:1.0
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis
    command: redis-server --port 6379
    container_name: redis
    hostname: redis_boot
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379
