version: '3.9'

services:
  redis:
    image: redis
    command: redis-server --port 6379
    container_name: redis
    hostname: redis_boot
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379
