export const EnvPath = {
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',
  TEST_DB_NAME: 'TEST_DB_NAME',
  SECRET_KEY: 'SECRET_KEY',
  REFRESH_TOKEN_EXPIRATION_TIME: 'REFRESH_TOKEN_EXPIRATION_TIME',
  ACCESS_TOKEN_EXIPIRATION_TIME: 'ACCESS_TOKEN_EXIPIRATION_TIME',
} as const;
